### PR TITLE
var_export bug with float(0) got fixed in PHP 7.0.2

### PR DESCRIPTION
**Pull request by Tobion**

### CODE REVIEW

**Comment by Ocramius** [comment]
Any way to add a test for it? I have 7.0.2 locally

**Comment by Tobion** [comment]
This is the test.

**Comment by Ocramius** [comment]
@Tobion meh, I need better glasses. Sorry!

**Comment by Tobion** [comment]
@Ocramius ping

**Comment by Tobion** [comment]
@Ocramius ping

**Comment by Ocramius** [comment]
@Tobion merged, thanks!

Backported into `1.6.x` via doctrine/cache@78ca4f3594e15a5adda0c7bcc01ae5343f0e429e

**Pull request merged**
