### PR TITLE
Test on PHP 7.4

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by greg0ire** [comment]
Please improve your commit message according to [the contributing guide](https://www.doctrine-project.org/contribute/index.html#working-on-topic-branches).

**Comment by GrahamCampbell** [comment]
This can be set by the merger.

**Comment by greg0ire** [comment]
Also, this should probably target the lowest supported branch where we have 7.4-snapshot

**Comment by GrahamCampbell** [comment]
Again, feel free to merge it where you want, with whatever commit message you want.

**Comment by greg0ire** [comment]
I can't, if I retarget this, your commit is not the only one which is going to come.

**Comment by GrahamCampbell** [comment]
You'd have to cherry-pick it when you merge. You can't just change the target in the UI.

**Comment by greg0ire** [comment]
> You can't just change the target in the UI.

That's exactly what I was saying.

**Comment by GrahamCampbell** [comment]
You can "merge" the commit into whatever branch you like though, just not using the UI.

**Comment by GrahamCampbell** [comment]
I mean, I don't even care if you just copy-paste the changes over or apply them yourself. It's such a tiny change.

**Comment by alcaeus** [comment]
Correct. We're going to apply this ourselves when we have the time to change this across our repos. As @greg0ire has said, this needs to be applied to the lowest supported branch to be merged via this UI. Since this isn't mergeable, I'm going to close out this PR. Feel free to open a new PR targeting the 1.10.x branch. Thanks for your contribution.

**Comment by greg0ire** [comment]
>  It's such a tiny change.

I'm sorry for being aggressive, the change being tiny is really what made me go the harsh way. I mean it's such a tiny change that doing it is dwarfed by other tasks like figuring out a good commit message (and I guess the Github UI was not pushing you towards that, I wish they could change it), but also, figuring out what the correct branch for this contribution is (and for this we have things to improve, like maybe configuring the default branch to something else than master). Please continue to contribute to Doctrine, and when you do, consider sending one PR and only one first before cloning it on other repositories, it will save time and energy for both of us.

Sorry again for the cold reception, and have a nice Christmas break!

**Comment by GrahamCampbell** [comment]
Sure thing. Have a good weekend, and Christmas. :)

**Comment by greg0ire** [comment]
Addressed in #338 . If you look closely you will notice I failed to pick the correct target branch at first :sweat_smile:

**Pull request closed without merging**
