### PR TITLE
PredisCache - added getClient method

### PR DESCRIPTION
**Pull request by ovr**
Hey!

Sometimes I needed to get PredisClient from Cache
So I can use 2 service in $di but I think this will be usefull

### CODE REVIEW

**Comment by Ocramius** [comment]
@ovr while I know the other adapters implement similar methods, I really suggest not going this way further on.
Unless there is a very strong need for the getter (can't inject), this should be avoided.

**Comment by Ocramius** [comment]
Indeed, after reading through it again, won't go down this way.

Closing

**Comment by ovr** [comment]
@Ocramius 
Main problem, Doctrine cache doesnt provide many method of Predis client

For now I am using something likes this

```php
$di['predis'] = function ($di) {return Predis();}
$di['cache'] = function($di) {new Doctrine\Cache\PRedis($di['predis'])}
```

But I hate this way, Why are you not interesting to allow merge this method? This will be very usefull, because I am using cache service only for Doctrine....

**Comment by Ocramius** [comment]
@ovr how you are doing it there is the right way..

**Pull request closed without merging**
