### PR TITLE
[enhancement] Predis cache improvement

### PR DESCRIPTION
**Pull request by sovaalexandr**
Allow usage of any Predis clients that implement proper interface

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Looks ready. Anything left to do?

**Comment by kimhemsoe** [comment]
:+1:

**Comment by sovaalexandr** [comment]
@TomasVotruba Don't think that anything else should be done here

**Comment by Ocramius** [comment]
The only thing to be added here is testing that a generic `ClientInterface` can be used. I'll do that locally now.

**Comment by Ocramius** [comment]
Merged via doctrine/cache@c76e6fb5b7eafae93c54f2b2e923ebc376938643 (with additional tests). Thanks!

**Pull request closed without merging**
