### PR TITLE
Adds a RunTime Exception for APCu Not Installed

### PR DESCRIPTION
**Pull request by LaurentMarquet**
Prevent user if APCu is not installed #224

### CODE REVIEW

**Comment by Ocramius** [comment]
Heya!

Can you try adding a test case expecting an exception?

Poke me if you need any guidance

**Comment by Laurent3170** [comment]
Yes I need guidance!

**Comment by Laurent3170** [comment]
Please :-)

**Comment by Ocramius** [comment]
@Laurent3170 you need something similar to https://github.com/doctrine/cache/blob/58f40845d8091b8cb768d6e3a49f685c8dff6928/tests/Doctrine/Tests/Common/Cache/ApcuCacheTest.php#L15, except that it must be a new test that is only skipped when APCu is actually enabled.

Use `$this->expectException(ExceptionType::class)` to verify that an exception is thrown at instantiation time.

**Comment by Laurent3170** [comment]
So... Teacher, here's my homework ;-)
Not really sure that it will work, but I don't know how to test...
```php
public function testApcuExtension() : void
    {
        if (! function_exists('apcu_fetch')) {
            $this->expectException(RuntimeException::ApcuCache);

            new ApcuCache();
        } else {
            $this->markTestSkipped('APCu is actually enabled');
        }
    }
```
I don't know neither if I can add the file `ApcuCacheTest.php` to this PR or if I must create a new one.
Thanks your help

**Comment by Ocramius** [comment]
@Laurent3170 a new test class is needed, as the original has a `$this->markTestSkipped()` call in `setUp()`. Just toss in a new file with a descriptive name :-)

**Comment by Laurent3170** [comment]
So I did another PR #227

**Comment by Ocramius** [comment]
Closing here, moved to #227

**Comment by Ocramius** [comment]
Actually, never mind, my mistake. The tests of #227 should be incorporated in this patch (just push to the same branch). As for the test itself, I'm providing a review on #227 and closing that one instead.

**Comment by Laurent3170** [comment]
I will only be able to look at this in 10-12 days. Thanks for all your time and information!

**Comment by Laurent3170** [comment]
I almost understand nothing... It is not really my domain, but I thank you for the time you spend to try to explain me. You should have did it faster by yourself :-(
I have commented on #227

**Comment by Ocramius** [comment]
> I almost understand nothing...

Just a little bit of patience :-)

 > It is not really my domain

You *really* need to make this your domain - testing is strictly needed for every software developer, so use this as a chance to get better at it :-)

**Comment by Laurent3170** [comment]
I agree, you're right ! Testing is really needed and I do some (should do more, specifically for calling forms...) for web page calls, not for "applications". I have to progress, but there are not a lot of tutorials about creating tests (or I haven't found them, as I haven't really searched...)
I started with Symfony, by myself with tutotials, 18 months ago, and I use Doctrine only on a basic level. Working with cache is almost "chinese" for me, for the time being, even if cache is really important.

But again I will not be able to look at it before 3-4 weeks... Impossible to work with three young children plus 2 older ones ;-)

My main problem  with that test is that I don't know how to run the test and then being able to debug it. For Symfony apps I use `phpunit` but here, I don't know...

Thanks for your encouragements!

**Comment by Ocramius** [comment]
@Laurent3170 this is also `phpunit`. Nobody is pushing you, just don't abandon it if you don't know how to continue: give it another shot when and if you have time.

It's OSS, there is nobody whipping you if you can't work on it immediately :-P

**Pull request closed without merging**
