### PR TITLE
ElasticSearch Doctrine Cache Adapter

### PR DESCRIPTION
**Pull request by eddiejaoude**

### CODE REVIEW

**Comment by Ocramius** [comment]
I'll rebase on merge.

**Comment by Ocramius** [comment]
Decided not to merge this, as it introduces a soft-dependency to another external library.

I suggest moving it to a bridge library not maintained by us, as we can't ensure stability of this component.

**Comment by Ocramius** [comment]
@eddiejaoude note that the code is perfectly ok, I just suggest to move this branch out of `doctrine/cache` and into a new library that depends (strictly) on `doctrine/cache` and the elasticsearch PHP client.

**Comment by eddiejaoude** [comment]
@Ocramius sure no problem.

**Pull request closed without merging**
