### PR TITLE
Add stats on hits/misses in redis caches

### PR DESCRIPTION
**Pull request by romainneutron**

### CODE REVIEW

**Comment by Ocramius** [comment]
@romainneutron can you test that those keys are not-null now? Basically an extension to https://github.com/doctrine/cache/blob/c2ab51e8f3c4a8170ca91b702e3789881dd2a6c2/tests/Doctrine/Tests/Common/Cache/CacheTest.php#L254

**Comment by romainneutron** [comment]
I've added tests, is it what you expected?

**Comment by Ocramius** [comment]
Looking good, thanks! Waiting for travis.

**Comment by Ocramius** [comment]
:+1:

**Pull request merged**
