### PR TITLE
Fix off-by-one accessing last object in list

### PR DESCRIPTION
**Pull request by robocoder**

### CODE REVIEW

**Comment by Ocramius** [comment]
@robocoder needs tests

**Comment by robocoder** [comment]
Oh, it isn't obvious that `$objectList[count($objectList)];` is NULL?  ;)

**Comment by Ocramius** [comment]
Can be as clear as the sky, but needs to be tested to prevent regressions.

**Comment by robocoder** [comment]
The unit test I committed is broken. I'll troubleshoot it later (tonight?).

**Comment by robocoder** [comment]
:taxa:

**Comment by robocoder** [comment]
The Travis failures are with php7.2 and RedisCache (not Riak).

**Comment by robocoder** [comment]
Rebased with master.

**Comment by Ocramius** [comment]
@guilhermeblanco I suppose this needs to be backported into the current release branch too...

**Pull request merged**
