### PR TITLE
Hotfix: mongo collection mocking fixes / 5.3 test failures

### PR DESCRIPTION
**Pull request by Ocramius**

### CODE REVIEW

**Comment by stof** [comment]
the APCu installation should be changed, to force it to install 4.x on PHP 5.5 and 5.6 (pecl will try to get the latest even though it requires PHP 7, as it does not have proper dependency resolution)

**Comment by Ocramius** [comment]
@stof yep, figured it out and already pushed

**Comment by stof** [comment]
@Ocramius what about installing APCu 5 for PHP 7 as it is supported now ?

**Comment by Ocramius** [comment]
@stof that already works, but `pecl` is broken on travis-ci atm

**Pull request merged**
