### PR TITLE
Ensure an index is set on the expiration field to enable automatic pu…

### PR DESCRIPTION
**Pull request by holtkamp**
As suggested in https://github.com/doctrine/cache/issues/139

### CODE REVIEW

**Comment by holtkamp** [comment]
Small ping on this, anything missing on having this merged?

**Comment by Tobion** [comment]
This will do an additional MongoDB request every time. Does not seem optimal. IMO this should be done only explicitly as it is a one time setup basically.

**Comment by Ocramius** [comment]
Pretty much agree with @Tobion here, but unsure on how to proceed on this.

**Comment by holtkamp** [comment]
agree with @Tobion as well, but not sure whether "only do this when required" is possible. Might be better as a configurable feature... 

Maybe a small test to see how this impacts performance makes sense? In my case the benefits outweigh the disadvantages 😉

**Comment by alcaeus** [comment]
Superseded by #221. Thanks @holtkamp for getting this started.

**Pull request closed without merging**
