### PR TITLE
Fix Redis cache typo

### PR DESCRIPTION
**Pull request by jandlouhy**

### CODE REVIEW

**Comment by Ocramius** [comment]
Yes, repository does not currently have any SA setup

**Comment by Ocramius** [comment]
Yes, repository does not currently have any SA setup

**Comment by jandlouhy** [comment]
@Ocramius I can, but I crated the branch from master so there are changes not related to the fix. Should I create new PR?

**Comment by Ocramius** [comment]
@jandlouhy probably faster, since you changed only few chars :-)

Closing here.

**Pull request closed without merging**
