### PR TITLE
Redis  MGET support

### PR DESCRIPTION
**Pull request by goetas**
Added redis and predis MGET support

### CODE REVIEW

**Comment by guilhermeblanco** [comment]
Patch is ok, but I have something needling my head this seems wrong.
What's the idea here? If we fetch N keys and cache only returns < N, you need to fill out the blanks with null values?

**Comment by goetas** [comment]
Looking at [this](https://github.com/doctrine/cache/blob/92642fc4902f1d4ac1b0e645152e833816767351/lib/Doctrine/Common/Cache/MultiGetCache.php#L36) the Predis implementation is correct, while the Redis implementation is not correct... i will fix it.

**Comment by guilhermeblanco** [comment]
array_filter should do the work then... =)

**Comment by goetas** [comment]
done

**Comment by Ocramius** [comment]
Very good: merging, but it will be in `1.5.0` only.

**Pull request merged**
