### PR TITLE
Enhancement - Improve CacheProvider inheritance: Version 2

### PR DESCRIPTION
**Pull request by mkovel**
I have considered your comments, I would like to offer you another variant

### CODE REVIEW

**Comment by Ocramius** [comment]
I would still not extend from this class if you need to use its internal components. Just rewrite from scratch.

**Comment by mkovel** [comment]
I don't understand what you don't like protected + final ?

**Comment by Ocramius** [comment]
The problem is that this approach enforces us to treat this API as a possible source of BC breaks, whereas we simply want to be able to rewrite or scrap it at any time.

Copying over the logic is perfectly fine.

**Comment by mkovel** [comment]
ok, i understood your opinion. tnx

**Comment by deeky666** [comment]
Closing as per discussion.

**Pull request closed without merging**
