### PR TITLE
Add example of using a PSR-6 cache wrapped in Doctrine Cache interface.

### PR DESCRIPTION
**Pull request by beberlei**
I want to add this explanation to the documentation and UPGRADE notice to help users upgrade more easily.

### CODE REVIEW

**Review by derrabus — APPROVED** [review]
Shall we target 1.12.x?

**Comment by SenseException** [comment]
Because 1.12 is still maintained, I'd also suggest that it should target 1.12.x.

**Comment by gnumoksha** [comment]
Hello. This is an important change. Are you planning to merge it soon?

Also:
1 - Is the `FilesystemAdapter` prefered in the same way the `PhpFileCache` was? [reference](https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/improving-performance.html#metadata-and-query-caches)
2 - Are you planning to update [this](https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/improving-performance.html#metadata-and-query-caches) and [this](https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/caching.html#phpfilecache)?

**Comment by alcaeus** [comment]
@gnumoksha I'll re-target 1.12 then merge, but haven't gotten to it yet.

As for the other questions, I believe you should raise them in a discussion in the ORM project (see https://github.com/doctrine/orm/discussions), as they relate to how ORM integrates caching based on this library, but not directly related to the library.

**Pull request merged**
