### PR TITLE
Removes support for PHP 5.x

### PR DESCRIPTION
**Pull request by railto**
Removes support for PHP 5.x from composer.json and .travis.yml

### CODE REVIEW

**Comment by bordeux** [comment]
why?

**Comment by Ocramius** [comment]
@bordeux PHP 5.x is now in security-only mode as per http://php.net/supported-versions.php

Older versions of the cache component will still be patched for security issues, but we're not maintaining active support for unsupported PHP versions.

**Comment by railto** [comment]
Closing as I do not have the ability to get this to work with HHVM tests

**Comment by Ocramius** [comment]
Reopening: still needs to happen, even if you don't work on the PR yourself.

**Comment by lcobucci** [comment]
Handled in #219 and #220

**Pull request closed without merging**
